#2 user auth
afes-website/manage-app pull request #12
Opened 2020-09-07 08:54 UTC by su8ru

close #2 

デバッグフェーズも終盤なので PR

- まれに localStorage の users が `{}` で上書きされる？
  再現が難しいことと、開発中に見たものなのでいまも発生するのかは怪しい

2020-09-08 06:26 UTC, Takeno-hito requested changes
- [ ] くるくるを出せ
- [x] enterでログインしろ
<!-- - [x] 人のPCを雑に扱うな -->

2020-09-08 06:38 UTC, Takeno-hito requested changes
ネットワークに接続できないときにからっぽになる @ibuki2003

2020-09-08 14:27 UTC, su8ru commented on src/pages/Login.tsx
> +    }, 500);
以下の理由から遅延をかけることが推奨されていますが、実際はごく短時間で処理が行われたときに一瞬だけ見えるのが不快なので遅延させてます

> Delaying appearance
> There are [3 important limits](https://www.nngroup.com/articles/response-times-3-important-limits/) to know around response time. The ripple effect of the `ButtonBase` component ensures that the user feels that the system is reacting instantaneously. Normally, no special feedback is necessary during delays of more than 0.1 but less than 1.0 second. After 1.0 second, you can display a loader to keep user's flow of thought uninterrupted.
> [Circular, Linear progress React components \- Material\-UI](https://material-ui.com/components/progress/)

2020-09-08 14:37 UTC, su8ru commented
Auth Class に JSDoc つけようと思ったけど面倒なのでやめた

2020-09-08 22:42 UTC, ibuki2003 requested changes

2020-09-08 22:42 UTC, ibuki2003 commented on src/components/BottomNav.tsx
> +    const menus: menuItem[] = commonMenus;
参照渡ししてる上コピー元を変更してしまっている

commonMenuもpushで実装したくない？

2020-09-08 22:42 UTC, ibuki2003 commented on src/components/BottomNav.tsx
> +  const commonMenus: menuItem[] = [
定数は外に出しちゃいたい(スコープとか面倒ですか？)

2020-09-09 02:17 UTC, su8ru commented on src/components/BottomNav.tsx
> +  const commonMenus: menuItem[] = [
上がいい？下がいい？

2020-09-09 02:18 UTC, ibuki2003 commented on src/components/BottomNav.tsx
> +  const commonMenus: menuItem[] = [
下に出したら怒られませんか? (上かな)

2020-09-09 02:27 UTC, su8ru commented on src/components/BottomNav.tsx
> +  const commonMenus: menuItem[] = [
怒られなかった
関数だから？

私は下派

2020-09-09 03:48 UTC, ibuki2003 approved these changes

2020-09-09 11:52 UTC, ibuki2003 approved these changes

2020-09-09 12:28 UTC, Takeno-hito approved these changes
ボトムのmenusの所改善できる余地がある気もするけど、api定義でenumがほしいという事だったので一回approve、杉山さんの反応によってはissueたてます

2020-09-09 12:42 UTC, Takeno-hito requested changes
Menu周りでforまわす

2020-09-09 15:10 UTC, su8ru commented
help wanted

わたし TS わかりません

```
Error:(46, 13) TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ admin: boolean; blogAdmin: boolean; blogWriter: boolean; exhibition: boolean; general: boolean; reservation: boolean; }'.
  No index signature with a parameter of type 'string' was found on type '{ admin: boolean; blogAdmin: boolean; blogWriter: boolean; exhibition: boolean; general: boolean; reservation: boolean; }'.
```

```
Error:(46, 39) TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ admin?: readonly MenuItem[] | undefined; blogAdmin?: readonly MenuItem[] | undefined; blogWriter?: readonly MenuItem[] | undefined; exhibition?: readonly MenuItem[] | undefined; general?: readonly MenuItem[] | undefined; reservation?: readonly MenuItem[] | undefined; }'.
  No index signature with a parameter of type 'string' was found on type '{ admin?: readonly MenuItem[] | undefined; blogAdmin?: readonly MenuItem[] | undefined; blogWriter?: readonly MenuItem[] | undefined; exhibition?: readonly MenuItem[] | undefined; general?: readonly MenuItem[] | undefined; reservation?: readonly MenuItem[] | undefined; }'.
```

```tsx
import React from "react";
import {
  BottomNavigation,
  BottomNavigationAction,
  createStyles,
  makeStyles,
  SvgIcon,
  Theme,
} from "@material-ui/core";
import routes from "@/libs/routes";
import { Link, useHistory } from "react-router-dom";
import { Assignment, Home, History } from "@material-ui/icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faDoorOpen, faDoorClosed } from "@fortawesome/free-solid-svg-icons";
import { AuthContext } from "@/libs/auth";
import { UserInfo } from "@afes-website/docs";

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      borderTop: "1px solid " + theme.palette.secondary.main,
    },
    selected: {
      color: theme.palette.secondary.main + " !important",
    },
    button: {
      boxSizing: "border-box",
    },
  })
);

const BottomNav: React.FunctionComponent = () => {
  const history = useHistory();
  const classes = useStyles();
  const [value, setValue] = React.useState(history.location.pathname);
  const auth = React.useContext(AuthContext);

  const get_menus = () => {
    const menus: MenuItem[] = [];
    menus.push(...commonMenus);
    type Keys = keyof UserInfo["permissions"];
    const _perm = auth.val.get_current_user()?.permissions;
    if (!_perm) return menus;
    for (const key of Object.keys(menuItems)) {
      if (key in _perm && key in menuItems)
        if (_perm[key]) menus.push(...menuItems[key]);
    }
    return menus;
  };

  const unListen = history.listen(() => {
    setValue(history.location.pathname);
  });

  React.useEffect(() => {
    return () => {
      unListen();
    };
  });

  if (auth.val.get_current_user_id())
    return (
      <BottomNavigation
        value={value}
        onChange={(event, newValue) => {
          setValue(newValue);
        }}
        className={classes.root}
        showLabels={true}
      >
        {get_menus().map(([label, route, Component]) => {
          return (
            <BottomNavigationAction
              label={label}
              icon={Component}
              className={classes.button}
              classes={{
                selected: classes.selected,
              }}
              key={label}
              component={Link}
              to={route}
              value={route}
            />
          );
        })}
      </BottomNavigation>
    );
  else return <React.Fragment />;
};

export default BottomNav;

type Keys = keyof UserInfo["permissions"];
type MenuItem = readonly [string, string, React.ReactNode];

const menuItems: { [key in Keys]?: readonly MenuItem[] } = {
  exhibition: [
    [
      "Enter",
      routes.ExhEnterScan.route.create({}),
      <SvgIcon key="Enter">
        <FontAwesomeIcon icon={faDoorOpen} />
      </SvgIcon>,
    ],
    [
      "Exit",
      routes.ExhExitScan.route.create({}),
      <SvgIcon key="Exit">
        <FontAwesomeIcon icon={faDoorClosed} />
      </SvgIcon>,
    ],
    [
      "History",
      routes.ExhScanHistory.route.create({}),
      <History key="History" />,
    ],
  ],
  general: [["History", "/general/history", <History key="History" />]],
  admin: [
    ["Reservation", "/admin/reservations", <Assignment key="reservation" />],
  ],
} as const;

const commonMenus: MenuItem[] = [
  ["Home", routes.Home.route.create({}), <Home key="Home" />],
];

```

2020-09-10 05:29 UTC, ibuki2003 approved these changes

2020-09-10 10:32 UTC, Takeno-hito approved these changes

2020-09-10 10:56 UTC, merged