#13 動的タイトル
afes-website/manage-app pull request #18
Opened 2020-09-13 09:16 UTC by su8ru

close #13 

index.html に置く静的なタイトルは `loading ...` とかも考えたんですが、どっちがいいんだろう

2020-09-13 14:08 UTC, Takeno-hito approved these changes

2020-09-13 14:41 UTC, ibuki2003 requested changes
useTitleでも用意して統一をしたい h1を置くなら返り値をstringにしてそれを読むとかもできるし(これは2箇所に定数を置くことへの対策)…

2020-09-14 11:14 UTC, ibuki2003 requested changes

2020-09-14 11:14 UTC, ibuki2003 commented on src/libs/title.ts
> +  }, []);
new titleを依存先に入れたいですね

2020-09-14 11:29 UTC, ibuki2003 approved these changes

2020-09-14 12:19 UTC, Takeno-hito approved these changes

2020-09-14 23:01 UTC, merged