#24 入退場スキャン
afes-website/manage-app pull request #30
Opened 2021-03-03 10:10 UTC by su8ru

close #24 

結構良さげな UI に仕上がっていると思います

Special Thanks @ibuki2003 

### To-do

- [ ] 返ってきた 退場時刻情報とかを表示する
- [ ] 読み込んだ History を下に表示する（G Pay みたいな感じ？）
- [ ] カメラ接続に失敗したときのエラー表示（カメラアイコンに斜線みたいなやつ出したい）

2021-03-04 06:32 UTC, Takeno-hito commented
予約情報を読み込んだタイミングでこの予約に合致するtermを表示してほしいです。

2021-03-12 09:52 UTC, su8ru commented
#24, #28 についてはだいたい終わりました
#31 もついでにこの PR でやってしまおうと思っています

@ibuki2003 @Takeno-hito review request だけ飛ばしてあります、少しずつ読んでいただけると…！

2021-03-12 11:59 UTC, ibuki2003 reviewed
コードスタイルのコメントしかないな 中身は開発中のを見てるから大丈夫だとおもいます

2021-03-12 11:59 UTC, ibuki2003 commented on src/assets/styles/theme.ts
>    deepmerge.all([
(このPRの話題じゃないかもだけど)エントリごとに分ける必要ない気がするんですがこの記法になってる理由があったりしますか?

2021-03-12 11:59 UTC, ibuki2003 commented on src/components/MaterialSvgIcons.tsx
> +import React from "react";
(このファイル)共通部分が多いのでpath文字列だけとっておいてカリー化したいです
(実は`type=`とかしちゃってもいいのではと思うなどしている)
面倒ならわたしがやる

2021-03-12 12:16 UTC, su8ru commented on src/assets/styles/theme.ts
>    deepmerge.all([
エントリ、options とか props とかを指してる？

だとしたら可読性以外の何物でもないです たしかにくっつけても良い気はするけど…どうだろう

2021-03-12 12:17 UTC, su8ru commented on src/components/MaterialSvgIcons.tsx
> +import React from "react";
賢そう おねがいします

2021-03-12 14:10 UTC, su8ru commented on src/assets/styles/theme.ts
>    deepmerge.all([
`ThemeBase` とかにするなら別で定義して merge したほうがわかりやすいな～って気持ちがしてこうしたのかもしれない

2021-03-13 14:40 UTC, su8ru commented
@Takeno-hito @ibuki2003 激重まぜこぜ PR にしてしまい申し訳ない、Ready for Review です

2021-03-14 05:03 UTC, ibuki2003 commented on src/assets/styles/theme.ts
>    deepmerge.all([
勘違いにやっと気づいた
`{ props }` と `{ overrides }` を分ける必要がないのでは、という話です
`{ props, overrides }`
そもそもdeepmergeが要らないように見える

2021-03-14 05:04 UTC, ibuki2003 submitted a review, later dismissed
LGTM

2021-03-14 05:18 UTC, su8ru commented on src/assets/styles/theme.ts
>    deepmerge.all([
Q. この記法になってる理由があったりしますか?
A. 私の知識不足です……

deepmerge はね、なんか不都合があってこうなってる気がする なんでだっけ

2021-03-14 05:38 UTC, ibuki2003 submitted a review, later dismissed

2021-03-14 17:16 UTC, su8ru commented
Ready for Review 2 :bow:

2021-03-15 02:09 UTC, Takeno-hito requested changes
とりあえずGeneral/EnterScanまで読んだ

あとNetWorkErrorの回収の仕方が場所によって微妙に異なる気がします(ちゃんとチェックしてないのであとで改めて指摘すると思う

2021-03-15 02:09 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +          setGuestCheckStatus("error");
set系はできる限り先頭に持っていきたいという話だったと伺っていますが

2021-03-15 02:09 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +          if (isNetworkError) networkErrorHandler(e);
```suggestion
            } else networkErrorHandler(e);
          } else networkErrorHandler(e);
```

の方がわかりやすそうじゃない?

2021-03-15 02:10 UTC, Takeno-hito commented on src/components/GuestScan.tsx
> +    if (guestId && guestId !== latestGuestId) {
OutDatedじゃん

2021-03-15 02:31 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      if (resultChipRef.current) resultChipRef.current.close();
これどういうなに

2021-03-15 02:38 UTC, su8ru commented
コンポーネント多すぎてついでに #26 やりたくなってきたけどそろそろ怒られそうなのでやめておきます

2021-03-15 02:42 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      if (resultChipRef.current) resultChipRef.current.close();
UseEffect使ってCheckStatusがloadingになった時に実行する、みたいな書き方はできませんか？という質問 そう書いた方がメンテナンスしやすいかなあ、って思った

2021-03-15 02:47 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      if (resultChipRef.current) resultChipRef.current.close();
処理があちこち分散するの、ちょっとうれしくなくない？

2021-03-15 02:48 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      if (resultChipRef.current) resultChipRef.current.close();
気持ちはカプセル化なんだけど

2021-03-15 03:19 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      if (resultChipRef.current) resultChipRef.current.close();
容易にできるけど、ここだけ分離して嬉しいことある？
success とか error とかは分離できないので、処理の見通しが悪くなるだけでは？

```ts
  useEffect(() => {
    if (rsvCheckStatus === "loading") {
      // error alert 非表示
      setErrorStatusCode(null);
      // rsv info 消去
      setTermInfo(null);
      // result chip 非表示
      if (resultChipRef.current) resultChipRef.current.close();
    }
  }, [rsvCheckStatus]);

  const handleRsvIdScan = (rsvId: string | null) => {
    // null check & 二重スキャン防止
    if (
      rsvId &&
      rsvId !== latestRsvId &&
      (rsvCheckStatus === null || rsvCheckStatus === "error")
    ) {
      setLatestRsvId(rsvId);
      // circular loading 表示
      setRsvCheckStatus("loading");
      // rsv id 検証
      api(aspida())
        .onsite.reservation._id(rsvId)
        .check.$get({
          headers: {
            Authorization: "bearer " + auth.get_current_user()?.token,
          },
        })
        .then((res) => {
          ...
```

2021-03-15 05:14 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      if (resultChipRef.current) resultChipRef.current.close();
たしかに微妙な気はしてきたけどもう少し考えさせて

2021-03-15 10:02 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      if (resultChipRef.current) resultChipRef.current.close();
描画に関心を持つ部分を分離した

```ts
  const handleScan = (data: string | null) => {
    if (data)
      switch (activeScanner) {
        case "rsv":
          handleRsvIdScan(data);
          break;
        case "guest":
          handleGuestIdScan(data);
          break;
      }
  };

  const handleRsvIdScan = (rsvId: string) => {
    // 二重スキャン防止
    if (
      rsvId !== latestRsvId &&
      (rsvCheckStatus === null || rsvCheckStatus === "error")
    ) {
      setLatestRsvId(rsvId);
      setRsvCheckStatus("loading");

      api(aspida())
        .onsite.reservation._id(rsvId)
        .check.$get({
          headers: {
            Authorization: "bearer " + auth.get_current_user()?.token,
          },
        })
        .then((res) => {
          // res.valid に関わらず無条件で Term 情報を取得
          setTermInfo(res.term);

          if (res.valid) {
            setRsvCheckStatus("success");
          } else if (
            res.status_code &&
            (statusCodeList as ReadonlyArray<string>).includes(res.status_code)
          ) {
            setRsvCheckStatus("error");
            setErrorStatusCode(res.status_code as StatusCode);
          }
        })
        .catch((e) => {
          setRsvCheckStatus("error");

          if (isAxiosError(e) && e.response?.status === 404)
            setErrorStatusCode("RESERVATION_NOT_FOUND");
          else networkErrorHandler(e);
        });
    }
  };

  useEffect(() => {
    switch (rsvCheckStatus) {
      case "loading":
        setErrorStatusCode(null);
        setTermInfo(null);
        if (resultChipRef.current) resultChipRef.current.close();
        break;
      case "success":
        setTimeout(() => {
          setActiveScanner("guest");
        }, 500);
        if (resultChipRef.current)
          resultChipRef.current.open(
            "success",
            `予約確認成功 / 予約 ID: ${latestRsvId}`,
            3000
          );
        break;
      case "error":
        if (resultChipRef.current)
          resultChipRef.current.open(
            "error",
            `予約確認失敗 / 予約 ID: ${latestRsvId}`
          );
        break;
    }
  }, [rsvCheckStatus, latestRsvId]);

  const handleGuestIdScan = (guestId: string) => {
    // 二重スキャン防止
    if (
      guestId !== latestGuestId &&
      guestId !== latestRsvId &&
      (guestCheckStatus === null || guestCheckStatus === "error")
    ) {
      setLatestGuestId(guestId);
      setGuestCheckStatus("loading");
      // guest id 検証 (rsv id は有効性を確認済)
      api(aspida())
        .onsite.general.enter.$post({
          body: {
            reservation_id: latestRsvId,
            guest_id: guestId,
          },
          headers: {
            Authorization: "bearer " + auth.get_current_user()?.token,
          },
        })
        .then((guest) => {
          setGuestCheckStatus("success");
          setPrevGuestInfo(guest);
        })
        .catch((e) => {
          setGuestCheckStatus("error");
          if (isAxiosError(e)) {
            const errorCode: unknown = e.response?.data.error_code;
            if (
              typeof errorCode === "string" &&
              (statusCodeList as ReadonlyArray<string>).includes(errorCode)
            ) {
              setErrorStatusCode(errorCode as StatusCode);
            } else networkErrorHandler(e);
          } else networkErrorHandler(e);
        });
    }
  };

  useEffect(() => {
    switch (guestCheckStatus) {
      case "loading":
        setErrorStatusCode(null);
        if (resultChipRef.current) resultChipRef.current.close();
        if (resultPopupRef.current) resultPopupRef.current.open();
        break;
      case "success":
        if (resultChipRef.current)
          resultChipRef.current.open(
            "success",
            `入場成功 / ゲスト ID: ${latestGuestId}`
          );
        break;
      case "error":
        if (resultChipRef.current)
          resultChipRef.current.open(
            "error",
            `入場失敗 / ゲスト ID: ${latestGuestId}`
          );
        break;
    }
  }, [guestCheckStatus, latestGuestId]);
```

2021-03-15 14:17 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      if (resultChipRef.current) resultChipRef.current.close();
良いと思います、ありがと

2021-03-15 14:35 UTC, ibuki2003 requested changes
しばらくレビューサボってごめんなさいでした
「そんなに重くない修正でしょ？」

2021-03-15 14:35 UTC, ibuki2003 commented on src/components/GuestScan.tsx
> +  const getActionName = useCallback(() => {
これメソッドじゃなくてよくないですか
(中で変数参照してるからwatchしてるの意味わからんってのはさておき)

2021-03-15 14:35 UTC, ibuki2003 commented on src/components/GuestScan.tsx
> +          if (isAxiosError(e)) {
早期returnでelseを減らしたいです 2回読んでるのとか嫌なので

2021-03-15 14:36 UTC, su8ru commented on src/components/GuestScan.tsx
> +  const getActionName = useCallback(() => {
useState と useEffect で管理？

2021-03-15 14:37 UTC, ibuki2003 commented on src/components/GuestScan.tsx
> +  const getActionName = useCallback(() => {
stateである必要すらないとおもいます

2021-03-15 14:39 UTC, ibuki2003 commented on src/components/GuestScan.tsx
> +  const getActionName = useCallback(() => {
stateというかhookかな 毎回switchかければいいという

2021-03-15 22:30 UTC, Takeno-hito requested changes

2021-03-16 04:05 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      (rsvCheckStatus === null || rsvCheckStatus === "error")
rsv success が出たあと直接入力を開いて入力されるのは guest id では

success 状態が 500 ms だけあるので、そこでハンドルしないようにしてる

2021-03-16 04:06 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      guestId !== latestRsvId &&
- null check は `handleScan()` でしてる
- rsv id との不一致も調べないと、api 通信が一瞬で済んだときに勢い余って guest id まで読んでしまいます

2021-03-16 05:18 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      (rsvCheckStatus === null || rsvCheckStatus === "error")
そこの500msの間に読み取りをするのを防ぐ理由はそんなない感じもするけど…後で読み直す

2021-03-16 06:25 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      (rsvCheckStatus === null || rsvCheckStatus === "error")
その 500ms のあいだに guest qr が引っかかるのでは

2021-03-16 07:31 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      (rsvCheckStatus === null || rsvCheckStatus === "error")
rsv check が success したあと、0.5 s 後には guest scan が始まるので、そこで rsv の変更を容認すると事故が発生しませんか（リストバンド qr を読ませてしまう、など）
そう考えると Fab の表示も切り替えた方がいい気がしてきたな

2021-03-16 07:36 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      (rsvCheckStatus === null || rsvCheckStatus === "error")
そもそもこの 0.5s は result を表示するために存在する間なので、そこでなんらかのアクションを許容するのは論外というか

2021-03-16 14:43 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      (rsvCheckStatus === null || rsvCheckStatus === "error")
0秒でもいいと思うけど必要でもないしいいや

2021-03-16 14:48 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      guestId !== latestRsvId &&
- 理解はしたが他の所が実際にそうなってるか確認しておきたいので、それが終わるまでちょっとこのconversation残させてください
- まぁそうか

2021-03-16 14:50 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      guestId !== latestRsvId &&
- いまやれよ

2021-03-16 14:56 UTC, su8ru commented on src/pages/general/EnterScan.tsx
> +      guestId !== latestRsvId &&
「他の所が実際にそうなってるか確認しておきたい」
これなに？？

2021-03-16 15:07 UTC, su8ru commented
@Takeno-hito @ibuki2003 re-req :bow:

2021-03-16 15:15 UTC, ibuki2003 submitted a review, later dismissed

2021-03-17 13:38 UTC, Takeno-hito requested changes

2021-03-17 13:38 UTC, Takeno-hito commented on src/components/GuestScan.tsx
> +      return "来場者が存在しません。";
```suggestion
return "IDに合致する来場者情報がありません。";
```

2021-03-17 13:38 UTC, Takeno-hito commented on src/components/GuestScan.tsx
> +      return "来場者は既に入室済みで、まだ退室していません。";
既に入室処理が完了しています。 //別に退室していないという条件をわざわざ見せる必要はない気がする

2021-03-17 13:38 UTC, Takeno-hito commented on src/components/GuestScan.tsx
> +      return "展示の人数制限に達しています。";
すでに展示の滞在者上限に達しています。

2021-03-17 13:38 UTC, Takeno-hito commented on src/components/GuestScan.tsx
> +      return "来場者は既に退場済みです。";
来場者は一度麻布から退場しています。必要に応じて近くの統制局員・総務局員にお問い合わせください。

2021-03-17 13:38 UTC, Takeno-hito commented on src/components/GuestScan.tsx
> +      return "展示が存在しません。総務局にお問い合わせください。";
内部エラーです(EXHIBITION_NOT_FOUND)。 総務局に至急お問い合わせください。

2021-03-17 13:55 UTC, Takeno-hito requested changes

2021-03-17 13:55 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      return "該当する予約が見つかりませんでした。予約 ID を再確認し、権限の強い人を呼んでください。";
合致する予約情報がありません。

2021-03-17 13:55 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      return "予約情報に問題があります。予約 ID を再確認し、権限の強い人を呼んでください。";
予約情報に不備があります。権限の強い人を呼んでください。

2021-03-17 13:55 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      return "この予約は入場時間外です。予約 ID を再確認し、権限の強い人を呼んでください。";
入場可能時間外です。入場可能時間帯を確認してください。

2021-03-17 13:55 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      return "この予約はすでに入場済みです。予約 ID を再確認し、権限の強い人を呼んでください。";
入場処理をすでに行っています。権限の強い人を呼んでください。

2021-03-17 13:55 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      return "リストバンド ID の形式が間違っています。別のリストバンドを試してください。";
リストバンド ID の形式が間違っています。

2021-03-17 13:55 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      return "このリストバンドはすでに登録済みです。別のリストバンドを試してください。";
使用済みのリストバンドです。権限の強い人を呼んでください。

2021-03-17 13:55 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      return "リストバンドの色と予約情報が一致しません。リストバンドの種類をもう一度確認してください。";
使用するリストバンドの種類が正しくありません。

2021-03-17 13:55 UTC, Takeno-hito commented on src/pages/general/EnterScan.tsx
> +      return "サーバーエラーが発生しました。総務局にお問い合わせください。";
**至急**総務局に

2021-03-17 14:21 UTC, Takeno-hito approved these changes

2021-03-17 14:22 UTC, ibuki2003 approved these changes

2021-03-17 14:23 UTC, merged