#40 滞在状況の表示
afes-website/manage-app pull request #43
Opened 2021-03-21 11:10 UTC by su8ru

close #40

- build: add recharts
- feat: display stay status
- feat: toggle shows limit
- feat: exh scan history
- fix: set initial value to reduce
- feat: show loading in exh scan history
- feat: show info when guest count is 0
- feat: improve HomeCard design
- feat: update home paragraph
- build: upgrade @afes-website/docs (alpha.7)
- fix: api update
- feat: add AllExhStatus
- build: add react-simple-pull-to-refresh
- feat: Pull to Refresh

2021-03-21 13:17 UTC, Takeno-hito commented
展示リストのソート手段が他にあってもいいかもしれない + 増やすんだったら全部について昇順降順が選べるようにしてもいいかも デフォはそのままで全然良いと思います
- 番号順
- 展示内の人数順
- 空席数順 (定員-現在数)
- 名前順

あと検索boxがあってもいいかもなと少し思った(が曖昧検索はbackが対応してないのでもしやるならdocsの変更から、、、)

2021-03-23 04:34 UTC, su8ru commented
@Takeno-hito 
> 展示リストのソート手段が他にほしい + 増やすんだったら全部について昇順降順が選べるようにしてもいいかも デフォはそのままで全然良いと思います
> 
> * 番号順
> * 展示内の人数順
> * 混雑度順=空席数順 (定員-現在数)

これらでニーズを満たせる気がするんですが、ソート順変更、要る…？
あと混雑度の比較関数はこれでいい？

- 展示番号順 : 展示番号順（昇順）
  ```ts
    if (a.info.room_id < b.info.room_id) return -1;
    if (a.info.room_id > b.info.room_id) return 1;
    return 0;
  ```
- 滞在人数順 : 滞在人数が多い順（降順）
  ```ts
  (sum_a - sum_b) * -1
  ```
- 混雑度順 : 空き枠が少ない順（空き枠数昇順・滞在人数降順）
  ```ts
  // ソート順序: (上限人数 - 滞在人数) 等しい場合は人数が多いほうが混雑
  return a.limit - sum_a - (b.limit - sum_b) || sum_b - sum_a;
  ```

2021-03-23 08:37 UTC, Takeno-hito submitted a review, later dismissed

2021-03-24 10:08 UTC, ibuki2003 requested changes
おそくなってごめんね

2021-03-24 10:08 UTC, ibuki2003 commented on src/pages/general/AllExhStatus.tsx
> +      return (sum_a - sum_b) * -1;
```suggestion
      return sum_b - sum_a;
```
```suggestion
      return -(sum_a - sum_b);
```

2021-03-24 10:08 UTC, ibuki2003 commented on src/pages/general/AllExhStatus.tsx
> +      );
reduceを1行にしたいけどprettierさんに怒られますかね

2021-03-24 10:08 UTC, ibuki2003 commented on src/pages/general/AllExhStatus.tsx
> +      return a.limit - sum_a - (b.limit - sum_b) || sum_b - sum_a;
```suggestion
      return (a.limit - sum_a) - (b.limit - sum_b) || (sum_b - sum_a);
```

こっちは好みです
```suggestion
      return a.limit - sum_a - (b.limit - sum_b) ?? sum_b - sum_a;
```

2021-03-24 10:21 UTC, su8ru commented on src/components/PullToRefresh.tsx
> +const PullToRefresh: React.FC<PullToRefreshProps> = (props) => {
スマホでの実機テストをしてないのがバレた やっぱ環境作らないとだめだ

衝突については完全に失念していました……
それ止められないのかなと思ったけど safari がカスだ

![image](https://user-images.githubusercontent.com/33474143/112293297-56603380-8cd5-11eb-9c8a-a1466e357543.png)

Twitter とかどうやって抑止してるんだろう………

2021-03-24 10:33 UTC, su8ru commented on src/components/StayStatus.tsx
> +          [...Array(5)].map((value, index) => (
それよりも同じ行に2つのコメントがついてることにびっくりしちゃった

2021-03-24 11:25 UTC, su8ru commented on src/pages/general/AllExhStatus.tsx
> +      );
私はこうは書かないので、Prettier さんが怒っているんだと思います
許容文字数増やしても良い気がするけど、それは結局別のところで同様の問題？が発生するので意味ないかな～～

2021-03-24 11:27 UTC, su8ru commented on src/pages/general/AllExhStatus.tsx
> +      return a.limit - sum_a - (b.limit - sum_b) || sum_b - sum_a;
前半の括弧は Prettier に外された、後半もきっとそう

2021-03-24 11:47 UTC, su8ru commented on src/components/PullToRefresh.tsx
> +const PullToRefresh: React.FC<PullToRefreshProps> = (props) => {
これ、たぶんかなりの泥沼になりそうなので、できれば Issue を分けたいんですが

- なかったことにする（feature として別 Issue）
- 衝突するけどとりあえず放置（bug として別 Issue）

どちらがいいとおもいますか @ibuki2003 @Takeno-hito

2021-03-24 11:49 UTC, ibuki2003 commented on src/components/PullToRefresh.tsx
> +const PullToRefresh: React.FC<PullToRefreshProps> = (props) => {
bugじゃないかなぁ(後者に一票)

2021-03-25 10:45 UTC, su8ru commented on src/components/PullToRefresh.tsx
> +const PullToRefresh: React.FC<PullToRefreshProps> = (props) => {
→ Issue #45

2021-03-25 10:45 UTC, su8ru commented on src/components/PullToRefresh.tsx
> +      {children}
一般的だしいいんじゃねのノリ

2021-03-25 10:46 UTC, su8ru commented on src/pages/general/AllExhStatus.tsx
> +    },
文字列です

2021-03-25 10:46 UTC, su8ru commented on src/components/PullToRefresh.tsx
> +  onRefresh: () => Promise<unknown>;
だめだった

2021-03-25 10:46 UTC, su8ru commented
@Takeno-hito @ibuki2003 re-req :bow:

2021-03-25 10:49 UTC, Takeno-hito submitted a review, later dismissed

2021-03-25 10:50 UTC, ibuki2003 requested changes

2021-03-25 10:50 UTC, ibuki2003 commented on src/components/StayStatus.tsx
> +  let data = Object.entries(statusCount)
sortするところまで別変数にいれてまとめたい

2021-03-25 10:52 UTC, su8ru commented on src/components/StayStatus.tsx
> +  let data = Object.entries(statusCount)
props の型を `ExhStatus["count"]` ではなくするということ？

2021-03-25 11:27 UTC, ibuki2003 commented on src/components/StayStatus.tsx
> +  let data = Object.entries(statusCount)
statusCountをソートしてる箇所が2つあるのでそれをまとめたいだけです
keysのほうは[0]だけ見ればいいはずだし

2021-03-25 14:06 UTC, su8ru commented
@ibuki2003 @Takeno-hito re-req :bow::bow:

2021-03-25 14:14 UTC, ibuki2003 approved these changes

2021-03-25 14:16 UTC, Takeno-hito approved these changes

2021-03-25 14:17 UTC, merged

2021-04-06 04:46 UTC, Takeno-hito approved these changes