#1 スキャン
afes-website/manage-app pull request #7
Opened 2020-08-30 12:58 UTC by su8ru

とりあえずいまできるところだけ

2020-08-30 13:27 UTC, Takeno-hito approved these changes

2020-08-30 13:36 UTC, Takeno-hito approved these changes
スマホから見ようとするとsslを通してないからとかでカメラをonにできなくてかなしい

2020-08-30 13:54 UTC, ibuki2003 requested changes
本実装で非同期になったら大幅改修することになりそうだな とか思いましたまる

2020-08-30 13:54 UTC, ibuki2003 commented on src/pages/exh/EnterScan.tsx
> +        autoHideDuration={10000}
長くないですか msでしょ (個人の感想です)

2020-08-30 13:54 UTC, ibuki2003 commented on src/pages/exh/EnterScan.tsx
> +  // 仮定義s
残すなら //TODO 消すなら消して本定義を書こう…

2020-08-30 13:54 UTC, ibuki2003 commented on src/pages/exh/ExitScan.tsx
> +  // 仮定義s
同じくTODO化?

2020-08-31 06:18 UTC, ibuki2003 approved these changes

2020-08-31 06:52 UTC, Takeno-hito approved these changes

2020-08-31 11:21 UTC, merged